project_id = "oemgqlxumfnstbjdiqmr"

[functions.grok-ai]
verify_jwt = true

[functions.get-sustainability-suggestions]
verify_jwt = true

[functions.claude-ai]
verify_jwt = true

[functions.send-email]
# Allow unauthenticated demo form submissions to send emails
verify_jwt = false

[functions.external-health-proxy]
verify_jwt = false
