
-- Batch 019: Records 361 to 380 EPD Materials Import
INSERT INTO unified_materials (
  name, description, material_type, carbon_footprint_kgco2e_kg,
  carbon_footprint_kgco2e_tonne, unit, category, region, tags,
  sustainability_score, recyclability, source, emission_scope,
  lifecycle_stage, carbon_intensity_category, environmental_impact_score,
  epd_registration_number, epd_publisher, epd_validity_date,
  lca_methodology, data_quality_rating, verification_status,
  source_hierarchy_level, green_star_compliant, local_availability,
  building_layers
) VALUES
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete KERB MACHINE (Boral) (NSW), (Wollongong) KERB MACHINE 25MPa 10MM',
  NULL,
  'Concrete (in-situ)',
  0.105833333333333,
  105.833333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/GGBFS blend (Boral) (NSW), (Wollongong) Normal Class GP/GGBFS blend 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0829166666666667,
  82.9166666666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  17,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/GGBFS/FA blend (Boral) (NSW), (Wollongong) Normal Class GP/GGBFS/FA blend 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0675,
  67.5,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  32,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 30% (Boral) (NSW), (Wollongong) ENVIROCRETE 30% 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0945833333333333,
  94.5833333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  5,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 40% (Boral) (NSW), (Wollongong) ENVIROCRETE 40% 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0845833333333333,
  84.5833333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  15,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE PLUS (Boral) (NSW), (Wollongong) ENVIROCRETE PLUS 25MPa',
  NULL,
  'Concrete (in-situ)',
  0.0825,
  82.5,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  17,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVISIA (Boral) (NSW), (Wollongong) ENVISIA 25MPa',
  NULL,
  'Concrete (in-situ)',
  0.075,
  75.0,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  25,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (TAS), (Hobart) Normal Class GP blend 25MPa',
  NULL,
  'Concrete (in-situ)',
  0.11625,
  116.25,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02337',
  'EPD Australasia',
  '2026-05-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVISIA (Boral) (TAS), (Hobart) ENVISIA 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.107083333333333,
  107.083333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02337',
  'EPD Australasia',
  '2026-05-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (TAS), (Launceston) Normal Class GP blend 25MPa',
  NULL,
  'Concrete (in-situ)',
  0.115833333333333,
  115.833333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02337',
  'EPD Australasia',
  '2026-05-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVISIA (Boral) (TAS), (Launceston) ENVISIA 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.104583333333333,
  104.583333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02337',
  'EPD Australasia',
  '2026-05-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, GP, Normal Class (WA Premix) (WA), (Perth)',
  NULL,
  'Concrete (in-situ)',
  0.135416666666667,
  135.416666666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Blend, Normal Class (WA Premix) (WA), (Perth)',
  NULL,
  'Concrete (in-situ)',
  0.121666666666667,
  121.66666666666701,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LC)50 (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.0683333333333333,
  68.3333333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  31,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LC)40 (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.0779166666666667,
  77.9166666666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  22,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LC)30 (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.1,
  100.0,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LCHP) (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.0833333333333333,
  83.3333333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  16,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LCP) (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.0883333333333333,
  88.3333333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  11,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Ready-Mix Concrete Normal class GP blend (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.11375,
  113.75,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Ready-Mix Concrete KERB MACHINE (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.0675,
  67.5,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  32,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
);
