
-- Batch 018: Records 341 to 360 EPD Materials Import
INSERT INTO unified_materials (
  name, description, material_type, carbon_footprint_kgco2e_kg,
  carbon_footprint_kgco2e_tonne, unit, category, region, tags,
  sustainability_score, recyclability, source, emission_scope,
  lifecycle_stage, carbon_intensity_category, environmental_impact_score,
  epd_registration_number, epd_publisher, epd_validity_date,
  lca_methodology, data_quality_rating, verification_status,
  source_hierarchy_level, green_star_compliant, local_availability,
  building_layers
) VALUES
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/FA blend (Boral) (NSW), (Newcastle) Normal Class GP/FA blend 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0916666666666667,
  91.6666666666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  8,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/GGBFS blend (Boral) (NSW), (Newcastle) Normal Class GP/GGBFS blend 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0833333333333333,
  83.3333333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  16,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 30% (Boral) (NSW), (Newcastle) ENVIROCRETE 30% 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0916666666666667,
  91.6666666666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  8,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 40% (Boral) (NSW), (Newcastle) ENVIROCRETE 40% 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0833333333333333,
  83.3333333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  16,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE PLUS (Boral) (NSW), (Newcastle) ENVIROCRETE PLUS 25MPa',
  NULL,
  'Concrete (in-situ)',
  0.0808333333333333,
  80.8333333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  19,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVISIA (Boral) (NSW), (Newcastle) ENVISIA 25MPa',
  NULL,
  'Concrete (in-situ)',
  0.0766666666666667,
  76.6666666666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  23,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete KERB MACHINE (Boral) (NSW), (Newcastle) KERB MACHINE 25MPa 10MM',
  NULL,
  'Concrete (in-situ)',
  0.105,
  105.0,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (NSW), (Sydney) Normal Class GP blend 25MPa',
  NULL,
  'Concrete (in-situ)',
  0.12,
  120.0,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (NSW), (Sydney) Normal Class GP blend 25MPa (2)',
  NULL,
  'Concrete (in-situ)',
  0.12,
  120.0,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (NSW), (Sydney) Normal Class GP blend 25MPa (3)',
  NULL,
  'Concrete (in-situ)',
  0.12,
  120.0,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/FA blend (Boral) (NSW), (Sydney) Normal Class GP/FA blend 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0958333333333333,
  95.8333333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  4,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/GGBFS blend (Boral) (NSW), (Sydney) Normal Class GP/GGBFS blend 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.085,
  85.0,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  15,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/GGBFS/FA blend (Boral) (NSW), (Sydney) Normal Class GP/GGBFS/FA blend 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0729166666666667,
  72.9166666666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  27,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 30% (Boral) (NSW), (Sydney) ENVIROCRETE 30% 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0958333333333333,
  95.8333333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  4,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 40% (Boral) (NSW), (Sydney) ENVIROCRETE 40% 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0870833333333333,
  87.0833333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  12,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE PLUS (Boral) (NSW), (Sydney) ENVIROCRETE PLUS 25MPa',
  NULL,
  'Concrete (in-situ)',
  0.0841666666666667,
  84.1666666666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  15,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVISIA (Boral) (NSW), (Sydney) ENVISIA 25MPa',
  NULL,
  'Concrete (in-situ)',
  0.0766666666666667,
  76.6666666666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  23,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete KERB MACHINE (Boral) (NSW), (Sydney) KERB MACHINE 25MPa 10MM',
  NULL,
  'Concrete (in-situ)',
  0.105,
  105.0,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (NSW), (Wollongong) Normal Class GP blend 25MPa',
  NULL,
  'Concrete (in-situ)',
  0.11875,
  118.75,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/FA blend (Boral) (NSW), (Wollongong) Normal Class GP/FA blend 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0945833333333333,
  94.5833333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  5,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
);
