
-- Batch 1: Records 1-1000 EPD Materials Import (Fixed with proper ENUM casting)
INSERT INTO unified_materials (
  name, description, material_type, carbon_footprint_kgco2e_kg,
  carbon_footprint_kgco2e_tonne, unit, category, region, tags,
  sustainability_score, recyclability, source, emission_scope,
  lifecycle_stage, carbon_intensity_category, environmental_impact_score,
  epd_registration_number, epd_publisher, epd_validity_date,
  lca_methodology, data_quality_rating, verification_status,
  source_hierarchy_level, green_star_compliant, local_availability,
  building_layers
) VALUES
(
  'Concrete, 20 MPa, in-situ, no reinforcement, (SE202E) (Ecopact) (Holcim) (SA) (Adelaide)',
  NULL,
  'Concrete (in-situ)',
  0.08625,
  86.25,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  91,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-04660',
  'EPD Australasia',
  '2027-01-27',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, (SE202E2) (Ecopact) (Holcim) (SA) (Adelaide)',
  NULL,
  'Concrete (in-situ)',
  0.08125,
  81.25,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  91,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-04660',
  'EPD Australasia',
  '2027-01-27',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, (R2020B)(GB) (BCG) (WA), (Perth)',
  NULL,
  'Concrete (in-situ)',
  0.08792,
  87.92,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  91,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05491',
  'EPD Australasia',
  '2027-12-15',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, (SE202E56) (Ecopact) (Holcim) (SA) (Adelaide)',
  NULL,
  'Concrete (in-situ)',
  0.08375,
  83.75,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  91,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-04660',
  'EPD Australasia',
  '2027-01-27',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, (VE202E56) (Ecopact) (Holcim) (VIC)',
  NULL,
  'Concrete (in-situ)',
  0.08667,
  86.67,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  91,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-04657',
  'EPD Australasia',
  '2027-09-26',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
);
