
-- Batch 2: Records 1 to 100 EPD Materials Import
INSERT INTO unified_materials (
  name, description, material_type, carbon_footprint_kgco2e_kg,
  carbon_footprint_kgco2e_tonne, unit, category, region, tags,
  sustainability_score, recyclability, source, emission_scope,
  lifecycle_stage, carbon_intensity_category, environmental_impact_score,
  epd_registration_number, epd_publisher, epd_validity_date,
  lca_methodology, data_quality_rating, verification_status,
  source_hierarchy_level, green_star_compliant, local_availability,
  building_layers
) VALUES
(
  'Concrete, 25 MPa, in-situ, no reinforcement, (SE252E) (Ecopact) (Holcim) (SA) (Adelaide)',
  NULL,
  'Concrete (in-situ)',
  0.09125,
  91.25,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  90,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-04661',
  'EPD Australasia',
  '2027-01-27',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (SE322E) (Ecopact) (Holcim) (SA) (Adelaide)',
  NULL,
  'Concrete (in-situ)',
  0.10250,
  102.50,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  89,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-04662',
  'EPD Australasia',
  '2027-01-27',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
);
