
-- Batch 034: Records 661 to 680 EPD Materials Import
INSERT INTO unified_materials (
  name, description, material_type, carbon_footprint_kgco2e_kg,
  carbon_footprint_kgco2e_tonne, unit, category, region, tags,
  sustainability_score, recyclability, source, emission_scope,
  lifecycle_stage, carbon_intensity_category, environmental_impact_score,
  epd_registration_number, epd_publisher, epd_validity_date,
  lca_methodology, data_quality_rating, verification_status,
  source_hierarchy_level, green_star_compliant, local_availability,
  building_layers
) VALUES
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (Adbri ConcreteN Class GP/GL32 MPa) (Adbri) (NSW)',
  NULL,
  'Concrete (in-situ)',
  0.139633333333333,
  139.633333333333,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05519',
  'EPD Australasia',
  '2028-03-31',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (Futurecrete®N Class GP/GL:FA32 MPa) (Adbri) (NSW)',
  NULL,
  'Concrete (in-situ)',
  0.123116666666667,
  123.116666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05519',
  'EPD Australasia',
  '2028-03-31',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (S32MPA 22MPA AT4 DAYS 20MM) (Adbri) (NSW)',
  NULL,
  'Concrete (in-situ)',
  0.1494,
  149.4,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05519',
  'EPD Australasia',
  '2028-03-31',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (S32MPA KERB&GUTTER MACHINE PLACED 10MM) (Adbri) (NSW)',
  NULL,
  'Concrete (in-situ)',
  0.128025,
  128.025,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05519',
  'EPD Australasia',
  '2028-03-31',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (S32MPA PT DECK 22MPA AT 5 DAYS 20MM) (Adbri) (NSW)',
  NULL,
  'Concrete (in-situ)',
  0.144975,
  144.975,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05519',
  'EPD Australasia',
  '2028-03-31',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (ACT), (Canberra) Normal Class GP blend 32MPa',
  NULL,
  'Concrete (in-situ)',
  0.130833333333333,
  130.833333333333,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/FA blend (Boral) (ACT), (Canberra) Normal Class GP/FA blend 32 MPa',
  NULL,
  'Concrete (in-situ)',
  0.109166666666667,
  109.166666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/GGBFS blend (Boral) (ACT), (Canberra) Normal Class GP/GGBFS blend 32 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0933333333333333,
  93.3333333333333,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  6,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 30% (Boral) (ACT), (Canberra) ENVIROCRETE 30% 32 MPa',
  NULL,
  'Concrete (in-situ)',
  0.109166666666667,
  109.166666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 40% (Boral) (ACT), (Canberra) ENVIROCRETE 40% 32 MPa',
  NULL,
  'Concrete (in-situ)',
  0.1,
  100.0,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE PLUS (Boral) (ACT), (Canberra) ENVIROCRETE PLUS 32MPa',
  NULL,
  'Concrete (in-situ)',
  0.095,
  95.0,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  5,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVISIA (Boral) (ACT), (Canberra) ENVISIA 32MPa',
  NULL,
  'Concrete (in-situ)',
  0.0820833333333333,
  82.0833333333333,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  17,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete KERB MACHINE (Boral) (ACT), (Canberra) KERB MACHINE 32MPa 10MM',
  NULL,
  'Concrete (in-situ)',
  0.122916666666667,
  122.916666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (NSW), (Newcastle) Normal Class GP blend 32MPa',
  NULL,
  'Concrete (in-situ)',
  0.1275,
  127.5,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/FA blend (Boral) (NSW), (Newcastle) Normal Class GP/FA blend 32 MPa',
  NULL,
  'Concrete (in-situ)',
  0.104166666666667,
  104.166666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 30% (Boral) (NSW), (Newcastle) ENVIROCRETE 30% 32 MPa',
  NULL,
  'Concrete (in-situ)',
  0.104166666666667,
  104.166666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 40% (Boral) (NSW), (Newcastle) ENVIROCRETE 40% 32 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0966666666666667,
  96.6666666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  3,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE PLUS (Boral) (NSW), (Newcastle) ENVIROCRETE PLUS 32MPa',
  NULL,
  'Concrete (in-situ)',
  0.0916666666666667,
  91.6666666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  8,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVISIA (Boral) (NSW), (Newcastle) ENVISIA 32MPa',
  NULL,
  'Concrete (in-situ)',
  0.0825,
  82.5,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  17,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/GGBFS blend (Boral) (NSW), (Newcastle) Normal Class GP/GGBFS blend 32 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0908333333333333,
  90.8333333333333,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  9,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
);
