
-- Batch 031: Records 601 to 620 EPD Materials Import
INSERT INTO unified_materials (
  name, description, material_type, carbon_footprint_kgco2e_kg,
  carbon_footprint_kgco2e_tonne, unit, category, region, tags,
  sustainability_score, recyclability, source, emission_scope,
  lifecycle_stage, carbon_intensity_category, environmental_impact_score,
  epd_registration_number, epd_publisher, epd_validity_date,
  lca_methodology, data_quality_rating, verification_status,
  source_hierarchy_level, green_star_compliant, local_availability,
  building_layers
) VALUES
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (QE327ETOP) (Ecopact) (Holcim) (QLD) (Brisbane)',
  NULL,
  'Concrete (in-situ)',
  0.10625,
  106.25,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-04658',
  'EPD Australasia',
  '2027-01-20',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (WE322E1)(Ecopact) (Holcim) (WA), (Perth Metro)',
  NULL,
  'Concrete (in-situ)',
  0.0945833333333333,
  94.5833333333333,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  5,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-03716',
  'EPD Australasia',
  '2026-11-25',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (WE324E1)(Ecopact) (Holcim) (WA), (Perth Metro)',
  NULL,
  'Concrete (in-situ)',
  0.0975,
  97.5,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  2,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-03716',
  'EPD Australasia',
  '2026-11-25',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (WE324E2)(Ecopact) (Holcim) (WA), (Perth Metro)',
  NULL,
  'Concrete (in-situ)',
  0.0979166666666667,
  97.9166666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  2,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-03716',
  'EPD Australasia',
  '2026-11-25',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (WE324E4)(Ecopact) (Holcim) (WA), (Perth Metro)',
  NULL,
  'Concrete (in-situ)',
  0.0979166666666667,
  97.9166666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  2,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-03716',
  'EPD Australasia',
  '2026-11-25',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (Adbri Concrete N Class GP:GL 32 MPa- Winnellie) (Adbri) (NT)',
  NULL,
  'Concrete (in-situ)',
  0.140416666666667,
  140.416666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05522',
  'EPD Australasia',
  '2028-03-31',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (QE322EXT1) (Ecopact) (Holcim) (QLD) (Brisbane)',
  NULL,
  'Concrete (in-situ)',
  0.1,
  100.0,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-04658',
  'EPD Australasia',
  '2027-01-20',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (NE321E1L2)(Ecopact) (Holcim) (NSW), (Sydney)',
  NULL,
  'Concrete (in-situ)',
  0.0741666666666667,
  74.1666666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  25,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02331',
  'EPD Australasia',
  '2026-04-08',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (QE322LPN2) (Ecopact) (Holcim) (QLD), Gold Coast',
  NULL,
  'Concrete (in-situ)',
  0.107916666666667,
  107.916666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05496',
  'EPD Australasia',
  '2028-04-22',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (QE322L652) (Ecopact) (Holcim) (QLD), Gold Coast',
  NULL,
  'Concrete (in-situ)',
  0.10875,
  108.75,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05496',
  'EPD Australasia',
  '2028-04-22',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (QE321L)(Ecopact) (Holcim) (QLD) (Sunshine Coast)',
  NULL,
  'Concrete (in-situ)',
  0.102083333333333,
  102.083333333333,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-04663',
  'EPD Australasia',
  '2027-09-12',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (QE322LOX) (Ecopact) (Holcim) (QLD), Gold Coast',
  NULL,
  'Concrete (in-situ)',
  0.103333333333333,
  103.333333333333,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05496',
  'EPD Australasia',
  '2028-04-22',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (Adbri Concrete N Class GP/GL 32 MPa) (Adbri) (VIC)',
  NULL,
  'Concrete (in-situ)',
  0.1125,
  112.5,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05520',
  'EPD Australasia',
  '2028-03-31',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (WE321EKC)(Ecopact) (Holcim) (WA), (Perth Metro)',
  NULL,
  'Concrete (in-situ)',
  0.110833333333333,
  110.833333333333,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-03716',
  'EPD Australasia',
  '2026-11-25',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (VE321EK6) (Ecopact) (Holcim) (VIC)',
  NULL,
  'Concrete (in-situ)',
  0.107083333333333,
  107.083333333333,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-04657',
  'EPD Australasia',
  '2027-09-26',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (VE321EKC) (Ecopact) (Holcim) (VIC)',
  NULL,
  'Concrete (in-situ)',
  0.1075,
  107.5,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-04657',
  'EPD Australasia',
  '2027-09-26',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (WE324EP1)(Ecopact) (Holcim) (WA), (Perth Metro)',
  NULL,
  'Concrete (in-situ)',
  0.09625,
  96.25,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  3,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-03716',
  'EPD Australasia',
  '2026-11-25',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (WE322E31)(Ecopact) (Holcim) (WA), (Perth Metro)',
  NULL,
  'Concrete (in-situ)',
  0.0925,
  92.5,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  7,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-03716',
  'EPD Australasia',
  '2026-11-25',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (Adbri Concrete N Class GP:GL 32 MPa- Katherine) (Adbri) (NT)',
  NULL,
  'Concrete (in-situ)',
  0.1425,
  142.5,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05522',
  'EPD Australasia',
  '2028-03-31',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, (Adbri Concrete N Class GP:GL 32 MPa- Alice Springs) (Adbri) (NT)',
  NULL,
  'Concrete (in-situ)',
  0.19125,
  191.25,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05522',
  'EPD Australasia',
  '2028-03-31',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
);
