
-- Batch 005: Records 81 to 100 EPD Materials Import
INSERT INTO unified_materials (
  name, description, material_type, carbon_footprint_kgco2e_kg,
  carbon_footprint_kgco2e_tonne, unit, category, region, tags,
  sustainability_score, recyclability, source, emission_scope,
  lifecycle_stage, carbon_intensity_category, environmental_impact_score,
  epd_registration_number, epd_publisher, epd_validity_date,
  lca_methodology, data_quality_rating, verification_status,
  source_hierarchy_level, green_star_compliant, local_availability,
  building_layers
) VALUES
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVISIA (Boral) (ACT), (Canberra) ENVISIA 20MPa',
  NULL,
  'Concrete (in-situ)',
  0.07375,
  73.75,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  26,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (ACT), (Canberra) Normal Class GP blend 20MPa',
  NULL,
  'Concrete (in-situ)',
  0.1125,
  112.5,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/FA blend (Boral) (NSW), (Newcastle) Normal Class GP/FA blend 20 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0829166666666667,
  82.9166666666667,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  17,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 30% 20 MPa (Boral) (NSW), (Newcastle) ENVIROCRETE 30% 20 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0829166666666667,
  82.9166666666667,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  17,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/GGBFS blend (Boral) (NSW), (Newcastle) Normal Class GP/GGBFS blend 20 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0783333333333333,
  78.3333333333333,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  21,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 40% (Boral) (NSW), (Newcastle) ENVIROCRETE 40% 20 MPa',
  NULL,
  'Concrete (in-situ)',
  0.07625,
  76.25,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  23,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE PLUS (Boral) (NSW), (Newcastle) ENVIROCRETE PLUS 20MPa',
  NULL,
  'Concrete (in-situ)',
  0.0745833333333333,
  74.5833333333333,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  25,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVISIA (Boral) (NSW), (Newcastle) ENVISIA 20MPa',
  NULL,
  'Concrete (in-situ)',
  0.0733333333333333,
  73.3333333333333,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  26,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (NSW), (Newcastle) Normal Class GP blend 20MPa',
  NULL,
  'Concrete (in-situ)',
  0.109583333333333,
  109.583333333333,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/FA blend (Boral) (NSW), (Sydney) Normal Class GP/FA blend 20 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0870833333333333,
  87.0833333333333,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  12,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/GGBFS blend (Boral) (NSW), (Sydney) Normal Class GP/GGBFS blend 20 MPa',
  NULL,
  'Concrete (in-situ)',
  0.08,
  80.0,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  20,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/GGBFS/FA blend (Boral) (NSW), (Sydney) Normal Class GP/GGBFS/FA blend 20 MPa',
  NULL,
  'Concrete (in-situ)',
  0.06625,
  66.25,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  33,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 30% (Boral) (NSW), (Sydney) ENVIROCRETE 30% 20 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0870833333333333,
  87.0833333333333,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  12,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 40% (Boral) (NSW), (Sydney) ENVIROCRETE 40% 20 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0795833333333333,
  79.5833333333333,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  20,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE PLUS (Boral) (NSW), (Sydney) ENVIROCRETE PLUS 20MPa',
  NULL,
  'Concrete (in-situ)',
  0.0775,
  77.5,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  22,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVISIA (Boral) (NSW), (Sydney) ENVISIA 20MPa',
  NULL,
  'Concrete (in-situ)',
  0.0733333333333333,
  73.3333333333333,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  26,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (NSW), (Sydney) Normal Class GP blend 20MPa',
  NULL,
  'Concrete (in-situ)',
  0.112916666666667,
  112.916666666667,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/FA blend (Boral) (NSW), (Wollongong) Normal Class GP/FA blend 20 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0854166666666667,
  85.4166666666667,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  14,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/GGBFS blend (Boral) (NSW), (Wollongong) Normal Class GP/GGBFS blend 20 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0783333333333333,
  78.3333333333333,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  21,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/GGBFS/FA blend (Boral) (NSW), (Wollongong) Normal Class GP/GGBFS/FA blend 20 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0616666666666667,
  61.6666666666667,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  38,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
);
