
-- Batch 036: Records 701 to 720 EPD Materials Import
INSERT INTO unified_materials (
  name, description, material_type, carbon_footprint_kgco2e_kg,
  carbon_footprint_kgco2e_tonne, unit, category, region, tags,
  sustainability_score, recyclability, source, emission_scope,
  lifecycle_stage, carbon_intensity_category, environmental_impact_score,
  epd_registration_number, epd_publisher, epd_validity_date,
  lca_methodology, data_quality_rating, verification_status,
  source_hierarchy_level, green_star_compliant, local_availability,
  building_layers
) VALUES
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVISIA (Boral) (TAS), (Hobart) ENVISIA 32 MPa',
  NULL,
  'Concrete (in-situ)',
  0.115,
  115.0,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02337',
  'EPD Australasia',
  '2026-05-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (TAS), (Launceston) Normal Class GP blend 32MPa',
  NULL,
  'Concrete (in-situ)',
  0.1275,
  127.5,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02337',
  'EPD Australasia',
  '2026-05-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVISIA (Boral) (TAS), (Launceston) ENVISIA 32 MPa',
  NULL,
  'Concrete (in-situ)',
  0.111666666666667,
  111.666666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02337',
  'EPD Australasia',
  '2026-05-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, GP, Normal Class (WA Premix) (WA), (Perth)',
  NULL,
  'Concrete (in-situ)',
  0.15125,
  151.25,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Blend, Normal Class (WA Premix) (WA), (Perth)',
  NULL,
  'Concrete (in-situ)',
  0.145416666666667,
  145.416666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, AQ1339, Special Class (WA Premix) (WA), (Perth)',
  NULL,
  'Concrete (in-situ)',
  0.16625,
  166.25,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, AQ1340, Special Class (WA Premix) (WA), (Perth)',
  NULL,
  'Concrete (in-situ)',
  0.16625,
  166.25,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, AQ2339, Special Class (WA Premix) (WA), (Perth)',
  NULL,
  'Concrete (in-situ)',
  0.132083333333333,
  132.083333333333,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, AQ2340, Special Class (WA Premix) (WA), (Perth)',
  NULL,
  'Concrete (in-situ)',
  0.1325,
  132.5,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LC)50 (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.0779166666666667,
  77.9166666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  22,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LC)40 (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.0895833333333333,
  89.5833333333333,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  10,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LC)30 (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.114166666666667,
  114.166666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LCHP) (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.0933333333333333,
  93.3333333333333,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  6,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LCP) (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.0995833333333333,
  99.5833333333333,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Ready-Mix Concrete Normal class GP blend (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.12375,
  123.75,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Ready-Mix Concrete KERB MACHINE (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.075,
  75.0,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  25,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Ready-Mix Concrete SLAG AGG CONCRETE MIX, (LC)50 (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.085,
  85.0,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  15,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Ready-Mix Concrete SLAG AGG CONCRETE MIX, (LC)40 (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.0929166666666667,
  92.9166666666667,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  7,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Ready-Mix Concrete SLAG AGG CONCRETE MIX, (LC)30 (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.110833333333333,
  110.833333333333,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 32 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LC)30 32MPa (Concrite) (NSW) (Southern Highlands, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.1125,
  112.5,
  'm³',
  '>25 MPa to ≤32 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>25 MPa to ≤32 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
);
