
-- Batch 006: Records 101 to 120 EPD Materials Import
INSERT INTO unified_materials (
  name, description, material_type, carbon_footprint_kgco2e_kg,
  carbon_footprint_kgco2e_tonne, unit, category, region, tags,
  sustainability_score, recyclability, source, emission_scope,
  lifecycle_stage, carbon_intensity_category, environmental_impact_score,
  epd_registration_number, epd_publisher, epd_validity_date,
  lca_methodology, data_quality_rating, verification_status,
  source_hierarchy_level, green_star_compliant, local_availability,
  building_layers
) VALUES
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 30% (Boral) (NSW), (Wollongong) ENVIROCRETE 30% 20 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0854166666666667,
  85.4166666666667,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  14,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 40% (Boral) (NSW), (Wollongong) ENVIROCRETE 40% 20 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0775,
  77.5,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  22,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE PLUS (Boral) (NSW), (Wollongong) ENVIROCRETE PLUS 20MPa',
  NULL,
  'Concrete (in-situ)',
  0.0754166666666667,
  75.4166666666667,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  24,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVISIA (Boral) (NSW), (Wollongong) ENVISIA 20MPa',
  NULL,
  'Concrete (in-situ)',
  0.0720833333333333,
  72.0833333333333,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  27,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (NSW), (Wollongong) Normal Class GP blend 20MPa',
  NULL,
  'Concrete (in-situ)',
  0.111666666666667,
  111.666666666667,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (TAS), (Hobart) Normal Class GP blend 20MPa',
  NULL,
  'Concrete (in-situ)',
  0.110416666666667,
  110.416666666667,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02337',
  'EPD Australasia',
  '2026-05-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (TAS), (Launceston) Normal Class GP blend 20MPa',
  NULL,
  'Concrete (in-situ)',
  0.110416666666667,
  110.416666666667,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02337',
  'EPD Australasia',
  '2026-05-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, GP, Normal Class (WA Premix) (WA), (Perth)',
  NULL,
  'Concrete (in-situ)',
  0.124166666666667,
  124.166666666667,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LC)50 (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.0620833333333333,
  62.0833333333333,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  37,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LC)40 (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.07125,
  71.25,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  28,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LC)30 (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.08875,
  88.75,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  11,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LCHP) (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.0770833333333333,
  77.0833333333333,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  22,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LCP) (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.0808333333333333,
  80.8333333333333,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  19,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Ready-Mix Concrete Normal class GP blend (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.10375,
  103.75,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Ready-Mix Concrete SLAG AGG CONCRETE MIX, (LC)50 (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.0658333333333333,
  65.8333333333333,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  34,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Ready-Mix Concrete SLAG AGG CONCRETE MIX, (LC)40 (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.0758333333333333,
  75.8333333333333,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  24,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Ready-Mix Concrete SLAG AGG CONCRETE MIX, (LC)30 (Concrite) (NSW) (Sydney Region, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.08375,
  83.75,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  16,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Ready-Mix Concrete (LC)30 20MPa (Concrite) (NSW) (Southern Highlands, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.0879166666666667,
  87.9166666666667,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  12,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Ready-Mix Concrete NORMAL CLASS GP BLEND (Concrite) (NSW) (Southern Highlands, NSW)',
  NULL,
  'Concrete (in-situ)',
  0.104583333333333,
  104.583333333333,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 20 MPa, in-situ, no reinforcement, Ready-Mix Concrete LC30 20MPa (Concrite) (ACT) (Canberra, ACT)',
  NULL,
  'Concrete (in-situ)',
  0.0925,
  92.5,
  'm³',
  '>10 MPa to ≤20 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>10 MPa to ≤20 MPa'],
  7,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05479',
  'EPD Australasia',
  '2027-02-28',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
);
