
-- Batch 017: Records 321 to 340 EPD Materials Import
INSERT INTO unified_materials (
  name, description, material_type, carbon_footprint_kgco2e_kg,
  carbon_footprint_kgco2e_tonne, unit, category, region, tags,
  sustainability_score, recyclability, source, emission_scope,
  lifecycle_stage, carbon_intensity_category, environmental_impact_score,
  epd_registration_number, epd_publisher, epd_validity_date,
  lca_methodology, data_quality_rating, verification_status,
  source_hierarchy_level, green_star_compliant, local_availability,
  building_layers
) VALUES
(
  'Concrete, 25 MPa, in-situ, no reinforcement, (VS252BHS2) (Holcim) (VIC)',
  NULL,
  'Concrete (in-situ)',
  0.0771875,
  77.1875,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  22,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-03712',
  'EPD Australasia',
  '2026-08-04',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, (QE252E)(Holcim) (QLD), (North QLD)',
  NULL,
  'Concrete (in-situ)',
  0.0873791666666667,
  87.3791666666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  12,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-03717',
  'EPD Australasia',
  '2026-12-09',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, (QE252E1)(Holcim) (QLD), (North QLD)',
  NULL,
  'Concrete (in-situ)',
  0.0874958333333333,
  87.4958333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  12,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-03717',
  'EPD Australasia',
  '2026-12-09',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, (QE252EFB1)(Holcim) (QLD), (North QLD)',
  NULL,
  'Concrete (in-situ)',
  0.0889625,
  88.9625,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  11,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-03717',
  'EPD Australasia',
  '2026-12-09',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, (QE251E)(Holcim) (QLD), (North QLD)',
  NULL,
  'Concrete (in-situ)',
  0.0894291666666667,
  89.4291666666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  10,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-03717',
  'EPD Australasia',
  '2026-12-09',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, (QE251E1)(Holcim) (QLD), (North QLD)',
  NULL,
  'Concrete (in-situ)',
  0.0896625,
  89.6625,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  10,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-03717',
  'EPD Australasia',
  '2026-12-09',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, (QE251EBMX)(Holcim) (QLD), (North QLD)',
  NULL,
  'Concrete (in-situ)',
  0.100404166666667,
  100.404166666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-03717',
  'EPD Australasia',
  '2026-12-09',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, (Adbri N ClassGP/GL 25 MPa) (Adbri) (SA)',
  NULL,
  'Concrete (in-situ)',
  0.0918875,
  91.8875,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  8,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05521',
  'EPD Australasia',
  '2028-03-31',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, (Adbri ConcreteN Class GP/GL:FA25 MPa) (Adbri) (NSW)',
  NULL,
  'Concrete (in-situ)',
  0.116020833333333,
  116.020833333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05519',
  'EPD Australasia',
  '2028-03-31',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, (S25MPAKERB&GUTTER MACHINE PLACED10MM) (Adbri) (NSW)',
  NULL,
  'Concrete (in-situ)',
  0.118779166666667,
  118.779166666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-05519',
  'EPD Australasia',
  '2028-03-31',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (ACT), (Canberra) Normal Class GP blend 25MPa',
  NULL,
  'Concrete (in-situ)',
  0.12,
  120.0,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/FA blend (Boral) (ACT), (Canberra) Normal Class GP/FA blend 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.09625,
  96.25,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  3,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP/GGBFS blend (Boral) (ACT), (Canberra) Normal Class GP/GGBFS blend 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0858333333333333,
  85.8333333333333,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  14,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 30% (Boral) (ACT), (Canberra) ENVIROCRETE 30% 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.09625,
  96.25,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  3,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE 40% (Boral) (ACT), (Canberra) ENVIROCRETE 40% 25 MPa',
  NULL,
  'Concrete (in-situ)',
  0.0875,
  87.5,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  12,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVIROCRETE PLUS (Boral) (ACT), (Canberra) ENVIROCRETE PLUS 25MPa',
  NULL,
  'Concrete (in-situ)',
  0.0841666666666667,
  84.1666666666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  15,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete ENVISIA (Boral) (ACT), (Canberra) ENVISIA 25MPa',
  NULL,
  'Concrete (in-situ)',
  0.0766666666666667,
  76.6666666666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  23,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete KERB MACHINE (Boral) (ACT), (Canberra) KERB MACHINE 25MPa 10MM',
  NULL,
  'Concrete (in-situ)',
  0.107916666666667,
  107.916666666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (NSW), (Newcastle) Normal Class GP blend 25MPa',
  NULL,
  'Concrete (in-situ)',
  0.12,
  120.0,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
),
(
  'Concrete, 25 MPa, in-situ, no reinforcement, Pre-mix Concrete Normal Class GP blend (Boral) (NSW), (Newcastle) Normal Class GP blend 25MPa (2)',
  NULL,
  'Concrete (in-situ)',
  0.116666666666667,
  116.666666666667,
  'm³',
  '>20 MPa to ≤25 MPa',
  'Australia',
  ARRAY['Concrete (in-situ)', '>20 MPa to ≤25 MPa'],
  0,
  NULL,
  'epd_import',
  'combined',
  'cradle-to-gate',
  'low',
  50,
  'S-P-02336',
  'EPD Australasia',
  '2026-04-01',
  'en_15804'::lca_methodology,
  7,
  'verified'::verification_status,
  'level_1_verified_epd'::data_source_level,
  true,
  true,
  ARRAY['Structure'::building_layer]
);
